services:
  - type: web
    name: splash-panel
    runtime: docker
    plan: free
    region: singapore
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: "5050"
